gallery/urls.py
# coding: utf-8

from __future__ import unicode_literals

from django.conf.urls import url

from . import views

app_name = 'gallery'

urlpatterns = [
    url(r'^$', views.GalleryIndexView.as_view(), name='index'),
    url(r'^year/(?P<year>\d{4})/$', views.GalleryYearView.as_view(), name='year'),
    url(r'^album/(?P<pk>[a-f\d\-]+)/$', views.AlbumView.as_view(), name='album'),
    url(r'^tags/$', views.TagsView.as_view(), name='tags'),
    url(r'^tags/(?P<pk>[a-f\d\-]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^export/(?P<pk>[a-f\d\-]+)/$', views.export_album, name='album-export'),
    url(r'^photo/(?P<pk>[a-f\d\-]+)/$', views.PhotoView.as_view(), name='photo'),
    url(r'^original/(?P<pk>[a-f\d\-]+)/$', views.original_photo, name='photo-original'),
    url(r'^(?P<preset>\w+)/(?P<pk>[a-f\d\-]+)/$', views.resized_photo, name='photo-resized'),
    url(r'^latest/$', views.latest_album, name='latest'),
]

gallery/templates/gallery/album_archive.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/gallery.css' %}">
{% endblock %}

{% block title %}{{ block.super }} - {{ title }}{% endblock %}

{% block content %}
<h1>{{ title }}</h1>

{% if user.is_authenticated %}
<form action="{% url 'gallery:index' %}" method="GET" class="album_filter">
{% if not perms.gallery.view %}
{% if show_public %}
<a href="?hide_public">{% trans "Hide public albums" %}</a>
{% else %}
<a href="?show_public">{% trans "Show public albums" %}</a>
{% endif %}
|
{% endif %}
<input type="text" name="q" required="required" size="20" value="{{ q }}">
<input type="submit" value="{% trans "Search" %}">
</form>
{% endif %}

<div class="album_year_list">
{% if q %}
{% blocktrans with query=q %}Results for <strong>{{ query }}</strong>{% endblocktrans %} | <a href="{% url 'gallery:index' %}">{% trans "See all albums" %}</a>
{% else %}
{% for date in date_list %}
<a href="{% url 'gallery:year' date.year %}">{{ date.year }}</a>
{% if not forloop.last %} | {% endif %}
{% endfor %}
{% endif %}
</div>

{% for album in latest %}
{% ifchanged album.date.year %}
<h2>{{ album.date.year }}</h2>
{% endifchanged %}
<h3 class="album_preview">
{{ album.display_name }}
<span class="album_count">{% blocktrans count album.photos_count as num_photos %}one photo{% plural %}{{ num_photos }} photos{% endblocktrans %}</span>
<span class="album_date">{{ album.date }}</span>
<span class="album_category">{% trans album.category %}</span>
</h3>
{% spaceless %}
<div class="photo_list">
{% for photo in album.preview %}
<a href="{{ album.get_absolute_url }}"><img src="{% url 'gallery:photo-resized' preset='thumb' pk=photo.pk %}" width="128" height="128" alt="{{ photo }}"></a>
{% empty %}
<p>{% trans "Sorry, you aren't authorized to view any photos in this album." %}</p>
{% endfor %}
</div>
{% endspaceless %}
{% empty %}
{% if q %}
<p>{% trans "Sorry, no albums match your query." %}</p>
{% else %}
<p>{% trans "Sorry, you aren't authorized to view any albums." %}</p>
{% endif %}
{% endfor %}

{% if is_paginated %}
<div class="album_page_list">
{% if page_obj.has_previous %}
<a href="{% url 'gallery:index' %}?page={{ page_obj.previous_page_number }}{% if q %}&amp;q={{ q }}{% endif %}">&larr;</a>
{% endif %}
{{ page_obj.number }} / {{ paginator.num_pages }}
{% if page_obj.has_next %}
<a href="{% url 'gallery:index' %}?page={{ page_obj.next_page_number }}{% if q %}&amp;q={{ q }}{% endif %}">&rarr;</a>
{% endif %}
</div>
{% endif %}

{% endblock %}

gallery/templates/gallery/album_archive_year.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/gallery.css' %}">
{% endblock %}

{% block title %}{{ block.super }} - {{ title }}{% endblock %}

{% block content %}
<h1>{{ title }}</h1>

{% if user.is_authenticated and not perms.gallery.view %}
<div class="album_filter">
{% if show_public %}
<a href="?hide_public">{% trans "Hide public albums" %}</a>
{% else %}
<a href="?show_public">{% trans "Show public albums" %}</a>
{% endif %}
</div>
{% endif %}


<div class="photo_nav">
{# next_year has the "previous" class and vice-versa because album ordering is reversed #}
{% if next_year %}
<a href="{% url 'gallery:year' next_year.year %}" class="previous">{{ next_year.year }}</a>
{% endif %}
<a href="{% url 'gallery:index' %}" class="up">{{ title }}</a>
{% if previous_year %}
<a href="{% url 'gallery:year' previous_year.year %}" class="next">{{ previous_year.year }}</a>
{% endif %}
</div>

<h2>{{ year.year }}</h2>
{% for album in album_list %}
<h3 class="album_preview">
{{ album.display_name }}
<span class="album_count">{% blocktrans count album.photos_count as num_photos %}one photo{% plural %}{{ num_photos }} photos{% endblocktrans %}</span>
<span class="album_date">{{ album.date }}</span>
<span class="album_category">{% trans album.category %}</span>
</h3>
{% spaceless %}
<div class="photo_list">
{% for photo in album.preview %}
<a href="{{ album.get_absolute_url }}"><img src="{% url 'gallery:photo-resized' preset='thumb' pk=photo.pk %}" width="128" height="128" alt="{{ photo }}"></a>
{% empty %}
<p>{% trans "Sorry, you aren't authorized to view any photos in this album." %}</p>
{% endfor %}
</div>
{% endspaceless %}
{% empty %}
<p>{% trans "Sorry, you aren't authorized to view any albums." %}</p>
{% endfor %}

{% if is_paginated %}
<div class="album_page_list">
{% if page_obj.has_previous %}
<a href="{% url 'gallery:year' year.year %}?page={{ page_obj.previous_page_number }}">&larr;</a>
{% endif %}
{{ page_obj.number }} / {{ paginator.num_pages }}
{% if page_obj.has_next %}
<a href="{% url 'gallery:year' year.year %}?page={{ page_obj.next_page_number }}">&rarr;</a>
{% endif %}
</div>
{% endif %}

{% endblock %}

gallery/templates/gallery/album_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/gallery.css' %}">
{% endblock %}

{% block title %}{{ block.super }} - {{ album.display_name }} - {{ album.date }}{% endblock %}

{% block content %}
<h1>{{ album.display_name }} - {{ album.date }}</h1>
<div class="photo_nav">
{# next_album has the "previous" class and vice-versa because album ordering is reversed #}
{% if next_album %}
<a href="{{ next_album.get_absolute_url }}" class="previous">{{ next_album.display_name }}</a>
{% endif %}
<a href="{% url 'gallery:year' album.date.year %}" class="up">{{ album.date.year }}</a>
{% if previous_album %}
<a href="{{ previous_album.get_absolute_url }}" class="next">{{ previous_album.display_name }}</a>
{% endif %}
</div>

{% spaceless %}
<div class="photo_list">
{% for photo in photos %}
<a href="{{ photo.get_absolute_url }}"><img src="{% url 'gallery:photo-resized' preset='thumb' pk=photo.pk %}" width="128" height="128" alt="{{ photo }}"></a>
{% empty %}
<p>{% trans "Sorry, you aren't authorized to view any photos in this album." %}</p>
{% endfor %}
</div>
{% endspaceless %}

<div class="album_export">
<a href="{% url 'gallery:album-export' pk=album.pk %}">{% trans "Download album" %}</a>
</div>

{% endblock %}

gallery/templates/gallery/photo_detail.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/gallery.css' %}">
{% endblock %}

{% block title %}{{ block.super }} - {{ photo.display_name }}{% endblock %}

{% block content %}
<h1>{{ photo.display_name }}</h1>
<!-- <div class="photo_nav"></div> -->

<div class="photo_detail">
<a href="{% url 'gallery:photo-original' pk=photo.pk %}">
    <img
        src="{% url 'gallery:photo-resized' preset='standard' pk=photo.pk %}"
        {# TODO: add some fallbacks for @alt #}
        alt="{{ photo }}"
    >
</a>
</div>

<div>
    <h2>Tags</h2>
    <ul>
        {% for tag in photo.tags.all %}
            <li><a href="{% url 'gallery:tag' pk=tag.id %}">{{ tag.name }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

gallery/templates/gallery/tag_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block title %}{{ tag.name }} | Tags{% endblock %}

{% block content %}
<h1>Photos Tagged with &ldquo;{{ tag.name }}&rdquo;</h1>

<p>{{ tag.description }}</p>

<a href="{% url 'gallery:tags' %}">See all tags</a>

<section>
    <div class="photo_list">
        {% for photo in photos %}
        <a href="{{ photo.get_absolute_url }}">
            <img
                src="{% url 'gallery:photo-resized' preset='thumb' pk=photo.pk %}"
                width="128"
                height="128"
                {# TODO: add some fallbacks for @alt #}
                alt="{{ photo.title }}"
            >
        </a>
        {% empty %}
        <p>{% trans "Sorry, you aren't authorized to view any photos with this tag." %}</p>
        {% endfor %}
    </div>
</section>
{% endblock %}

gallery/templates/gallery/tag_list.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %}{{ title }}{% endblock %}


{% block content %}
<h1>{{ title }}</h1>

<section>
    <ul>
    {% for tag in tags %}
        <li><a href="{% url 'gallery:tag' pk=tag.id %}">{{ tag.name }}</a></li>
    {% endfor %}
    </ul>
</section>
{% endblock content %}